blank_issues_enabled: false
contact_links:
  - name: Question/Support/Other
    url: https://discourse.jupyter.org/c/jupyterlab/17
    about: If you have a usage question
  - name: Chat with JupyterLab devs
    url: https://gitter.im/jupyterlab/jupyterlab
    about: Ask short questions about using or creating widgets
  - name: Bug in Core JupyterLab
    url: https://github.com/jupyterlab/jupyterlab/issues/new/choose
    about: If the bug or request concern the core JupyterLab code
